export const queryKeys = {
  Attachment: 'Attachment',
  Attachments: 'Attachments',
  DomainExists: 'DomainExists',
  DomainVerificationCode: 'DomainVerificationCode',
  Plans: 'Plans',
  Workflows: 'Workflows',
  Emails: 'Emails',
  Email: 'Email',
  EmailHeader: 'EmailHeader',
  Domain: 'Domain',
  DomainDNS: 'DomainDNS',
  User: 'user',
  CustomerExists: 'CustomerExists',
  Cards: 'Cards',
  PreviewInvoice: 'PreviewInvoice',
  DNSStatus: 'DNSStatus',
  Invoices: 'Invoices',
  Subscription: 'Subscription',
  Contacts: 'Contacts',
  Tags: 'Tags',
  EventTags: 'EventTags',
  EventNote: 'EventNote',
  EventNotes: 'EventNotes',
  CalendarEvents: 'CalendarEvents',
  CalendarEvent: 'CalendarEvent',
  Users: 'Users',
  Attendees: 'Attendees',
  OrgSchema: 'OrgSchema',
  CompanyLogo: 'CompanyLogo',
  CompanySettings: 'CompanySettings',
  SearchEmails: 'Emails',
  UserSettings: 'UserSettings',
  DeleteAttendees: 'DeleteAttendees',
  WorkflowDocuments: 'WorkflowDocuments',
  updateUserPassword: 'updateUserPassword',
  FolderList: 'FolderList',
  FlagEmail: 'FlagEmail',
  Rules: 'Rules',
  ProfilePicture: 'ProfilePicture',
  UserEmailGroups:'UserEmailGroups',
  UserRules:'UserRules',
  CreateEmailGroups:'CreateEmailGroups',
  EmailGroupById:'EmailGroupById',
};
