export { Home } from './Home';
export { Registration } from './Registration';
export { SignIn } from './SignIn';
export { PurchasePlan } from './PurchasePlan';
export { Dashboard } from './Dashboard';
export { Workspace } from './Workspace';
export { SingleEmail } from './SingleEmail';
export { NotesApp } from './NotesApp';
export { ProfileSetting } from './ProfileSetting/ProfileSetting';
export { UserDashboard } from './UserDashboard';
export { ForgetPassword } from './ForgetPassword';
export { WorkflowApp } from './WorkflowApp';
export {PricingPlan} from './PricingPlan';
export {Feedback} from './Feedback';
export {PrivacyPolicyPage} from './PrivacyPolicyPage';
export {TermsandConditionPage} from './TermsandConditionPage';
export {NewsIntroPage} from './NewsIntroPage';
export {NewsManagementPage} from './NewsManagementPage';
export {MeetBlue} from './MeetBlue';